### ISSUE TITLE
nothing works...

### ISSUE THREAD

**Issue by papaformigas** [FortniteFevers/AutoLeak#17]
I run this autoleak in windows and get lot of python errors.. can run a single option without an error... set it up correctly but all errors... beta and non beta...

**Comment by Kraypex** [comment]
install modules/library?

**Comment by papaformigas** [comment]
All hangs man... when generating item shop image it hangs, when getting updates loops... I setu up as another language rather than English and the icons are in English and not the language in the config file...

**Comment by papaformigas** [comment]
Done generating items! Merging images...
Traceback (most recent call last):
  File "C:\Fortnite\AutoLeak-beta\AutoLeak-beta\ALmodules\largeIconType.py", line 42, in large_merger
    shutil.rmtree('icons')
NameError: name 'shutil' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 3046, in <module>
    generate_cosmetics()
  File "bot.py", line 755, in generate_cosmetics
    return largeicontype(useFeaturedIfAvaliable, language)
  File "C:\Fortnite\AutoLeak-beta\AutoLeak-beta\ALmodules\largeIconType.py", line 360, in largeicontype
    large_merger()
  File "C:\Fortnite\AutoLeak-beta\AutoLeak-beta\ALmodules\largeIconType.py", line 45, in large_merger
    os.makedirs('icons')
  File "C:\Users\migue\AppData\Local\Programs\Python\Python37\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Impossível criar um ficheiro quando esse ficheiro já existe: 'icons'

**Comment by papaformigas** [comment]
TRhis is a very common error i get...

>> 11
Traceback (most recent call last):
  File "C:\Users\migue\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\migue\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\migue\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\migue\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 3066, in <module>
    shop_sections(sections_image, BotDelay, BG_Color, api, namelol, watermark, language)
  File "C:\Fortnite\AutoLeak-beta\AutoLeak-beta\ALmodules\shopsections.py", line 55, in shop_sections
    newsData = response.json()['data']['hash']
  File "C:\Users\migue\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by papaformigas** [comment]
Also when i ask to merge images it just merge 6 only... the icons folder receives all kind of files also... the shop images and the updates also.. is itg possible to make different folders for them.. because when i ask to merge comes up all mix together... or should i remove all pictures every time i want to do something different? 
Anothert issue is the watermark is not coming in the images.. the config file has the path"images/watermark..png" but then there is no image folder... what is the path where i should put m,y watermark?

**Comment by papaformigas** [comment]
Hey man I was in your scripts bot and discovered that the URLs you use dont work anymore.. the fn-api.com is not working anymore, thats maybe why some features do not work...

**Comment by papaformigas** [comment]
Another bug?? the site fn-api.com is not working.. maybe is because of that no?

Checking for a change in cosmetics... (1)
Checking for a change in cosmetics... (2)
Checking for a change in cosmetics... (3)
Checking for a change in cosmetics... (4)
Checking for a change in cosmetics... (5)
Checking for a change in cosmetics... (6)
Checking for a change in cosmetics... (7)
Checking for a change in cosmetics... (8)
Checking for a change in cosmetics... (9)
Checking for a change in cosmetics... (10)
Checking for a change in cosmetics... (11)
Checking for a change in cosmetics... (12)
Checking for a change in cosmetics... (13)
Checking for a change in cosmetics... (14)
Checking for a change in cosmetics... (15)
Checking for a change in cosmetics... (16)
Checking for a change in cosmetics... (17)
Checking for a change in cosmetics... (18)
Checking for a change in cosmetics... (19)
Checking for a change in cosmetics... (20)
Checking for a change in cosmetics... (21)
Checking for a change in cosmetics... (22)
Checking for a change in cosmetics... (23)
Checking for a change in cosmetics... (24)

**Comment by papaformigas** [comment]
Any solution?

**Comment by papaformigas** [comment]
> I'll look into it later today, and I'll get back to you with how to fix it.

SO??? ... NO REPLY???

**Comment by papaformigas** [comment]
i DOPNT THINK THESE PYTHON SCRIPTS ARE WORKING ... THERE ARE ERROS EVERYWHERE... CANT RUN NOTHING WITHOUT ERRORS... THERES NO POINT HAVING THIS ON GITHUB REALY... JUST A WASTE OF TIME...

**Comment by Dinoo3D** [comment]
L bozo

**Comment by papaformigas** [comment]
> L bozo

???
