### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by Artlfmj** [FortniteFevers/AutoLeak#5]
sh: cls: command not found
sh: TITLE: command not found
Traceback (most recent call last):
  File "bot.py", line 72, in <module>
    Mbox('AutoLeak - Created by Fevers.', f'Hey There! Welcome to AutoLeak, the easiest way to Auto-Leak Fortnite. \nMake sure to join our discord by clicking the OK button!\n\n\nYou are on AutoLeak version v{currentVersion}!', 0)
  File "bot.py", line 71, in Mbox
    return ctypes.windll.user32.MessageBoxW(0, text, title, style)
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by MyNameIsDark01** [comment]
are u launching it on linux?

**Comment by Artlfmj** [comment]
I was

Le dim. 4 juil. 2021 à 18:22, MyNameIsDark01 ***@***.***> a
écrit :

**Comment by MyNameIsDark01** [comment]
I know why u have this errors, it's due to MessageBox that's created on Windows to redirect users to AutoLeak's discord. Download it from this [fork](https://github.com/MyNameIsDark01/AutoLeak) and let me know if u have other issues.
