### ISSUE TITLE
ModuleNotFoundError : No Module Named 'modules'

### ISSUE THREAD

**Issue by hassanos123** [FortniteFevers/AutoLeak#7]
please fix this asap

**Comment by FortniteFevers** [comment]
If you are having a module not found error and it isn't being resolved, please go to this file path:
**C:\Users\USERNAME\AppData\Local\Programs\Python\PYTHON_VERSION** then go into the scripts folder.

While in the scripts folder, click on the file path as shown here
![image](https://user-images.githubusercontent.com/47673608/135528933-9e7e56fe-44fa-4d87-9324-b715e38a2f35.png)

and type in cmd
![image](https://user-images.githubusercontent.com/47673608/135528967-a37b70da-f9c8-4f8d-9873-d7f6213851ea.png)

then type pip install (module) and your done.
